### ISSUE TITLE
No delay between execution of commands

### ISSUE THREAD

**Issue by konstantinhirschfeld** [ChristopherRogers1991/mycroft_routine_skill#7] opened 2020-02-26 20:08 UTC
When executing the routine Mycroft doesnt wait for one action to stop before it starts a new one, leading to wierd sentence structure and incomplete anouncements.

**Comment by ChristopherRogers1991** [comment] 2020-02-27 02:12
This is a duplicate of #4. I'm going to close this out, in favor of that issue (which has some more details). I've just attempted a fix and pushed it to a branch - I'll tag you there, and provide details for testing.

**Closed as completed by ChristopherRogers1991** 2020-02-27 02:12 UTC
